---
# - name: install needed repo (grumbeul...)
#   shell: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
#   ignore_errors: yes

- name: install dependencies
  yum: >
    name="{{ item }}" 
    state=latest
  with_items:
    - realmd
    - samba
    - samba-common
    - samba-winbind
    - samba-winbind-clients
    - samba-winbind-krb5-locator
    - oddjob
    - oddjob-mkhomedir
    - ntp
    - ntpdate
    - krb5-workstation
    - cifs-utils
    - pam_mount

# - name: updating ntp.conf
#   lineinfile: >
#     dest=/etc/ntp.conf
#     insertafter="^server 3.centos.pool.ntp.org iburst"
#     line="server ntp.uhi.ac.uk in ntp.conf"

# - name: sync /w ntp server
#   shell: ntpdate ntp.uhi.ac.uk

- name: minimal authconfig run
  shell: authconfig --disableldap --disablenis --disableipav2 --enablewinbind --disablemd5 --enableshadow --disableldapauth --disablekrb5 --disablefingerprint --enablewinbindauth --enablelocauthorize --updateall
  ignore_errors: yes

- name: overwrite smb.conf
  copy: >
    src=smb.conf
    dest=/etc/samba/
    owner=root 
    group=root 
    mode=0644

- name: overwrite krb5.conf
  copy: >
    src=krb5.conf
    dest=/etc/    
    owner=root 
    group=root 
    mode=0644

- name: overwrite PAM system conf
  copy: >
    src=system-auth-ac
    dest=/etc/pam.d/
    owner=root 
    group=root 
    mode=0644

- name: overwrite PAM passwd conf
  copy: >
    src=password-auth-ac
    dest=/etc/pam.d/
    owner=root 
    group=root 
    mode=0644